name: First Workflow
on: workflow_dispatch
jobs:
  first-job: #not reserved name
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: 
          echo "Hello World1!"
          echo "Hello World2!"
          echo "Hello World3!"
      - name: Print goodbye
        run: echo "Done- bye!"
